// <auto-generated />
using EFCore_Cidades.Dados;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace EFCore_Cidades.Migrations
{
    [DbContext(typeof(CidadesContexto))]
    partial class CidadesContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFCore_Cidades.Negocio.Cidades", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EstadoCalamidade")
                        .HasColumnName("EstadoCalamidade")
                        .HasColumnType("bit");

                    b.Property<double>("ImpostoSobreProduto")
                        .HasColumnName("ImpostoSobreProduto")
                        .HasColumnType("float");

                    b.Property<string>("Nome")
                        .HasColumnName("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Populacao")
                        .HasColumnName("Populacao");

                    b.Property<double>("TaxaCriminalidade")
                        .HasColumnName("TaxaCriminalidade")
                        .HasColumnType("float");

                    b.Property<DateTime>("UltimaAtualizacao")
                        .HasColumnType("datetime2(7)");

                    b.HasKey("Id");

                    b.ToTable("Cidades");
                });
#pragma warning restore 612, 618
        }
    }
}
